version: '2'

services:
  sagemath:
    image: sagemath/sagemath:latest
    container_name: sagemath
    command: sage-jupyter --notebook-dir=/notebooks
    ports:
      - 8888:8888
    restart: "no"
    volumes:
      - ./notebooks:/notebooks

